// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZo0pW0Xa7KEg0RekW8IMIlERi647AIIo',
    appId: '1:646042829721:web:e269e93da12b13a5dc4908',
    messagingSenderId: '646042829721',
    projectId: 'taskmanagerapp-9f056',
    authDomain: 'taskmanagerapp-9f056.firebaseapp.com',
    databaseURL: 'https://taskmanagerapp-9f056-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taskmanagerapp-9f056.appspot.com',
    measurementId: 'G-LE6G8RFLC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6pg5XV9zGOzy-Pe3ZhVFPjKWaDIKesQs',
    appId: '1:646042829721:android:e6b9fe28fa0295d4dc4908',
    messagingSenderId: '646042829721',
    projectId: 'taskmanagerapp-9f056',
    databaseURL: 'https://taskmanagerapp-9f056-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taskmanagerapp-9f056.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0HEjU3XuZd1ySrQbyJ-GjJYX9Ox_L_z0',
    appId: '1:646042829721:ios:9a005e40ccd56388dc4908',
    messagingSenderId: '646042829721',
    projectId: 'taskmanagerapp-9f056',
    databaseURL: 'https://taskmanagerapp-9f056-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taskmanagerapp-9f056.appspot.com',
    iosBundleId: 'com.example.taskmanageapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0HEjU3XuZd1ySrQbyJ-GjJYX9Ox_L_z0',
    appId: '1:646042829721:ios:9a005e40ccd56388dc4908',
    messagingSenderId: '646042829721',
    projectId: 'taskmanagerapp-9f056',
    databaseURL: 'https://taskmanagerapp-9f056-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taskmanagerapp-9f056.appspot.com',
    iosBundleId: 'com.example.taskmanageapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZo0pW0Xa7KEg0RekW8IMIlERi647AIIo',
    appId: '1:646042829721:web:41a35202476f1d3edc4908',
    messagingSenderId: '646042829721',
    projectId: 'taskmanagerapp-9f056',
    authDomain: 'taskmanagerapp-9f056.firebaseapp.com',
    databaseURL: 'https://taskmanagerapp-9f056-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taskmanagerapp-9f056.appspot.com',
    measurementId: 'G-YDBSP9FHSF',
  );
}
